title: 4d105s25p3d的主页
SEOTitle: 4d105s25p3的博客 | 4d105s25p3 Blog
header-img: ""
email: ""
description: ""
keyword: ""
url: "https://4d105s25p3.github.io"
baseurl: ""
theme: jekyll-theme-cayman

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1